lib/routing/opDynamicAclRoute.class.php

Bug ticket https://redmine.openpne.jp/issues/3507
BP ticket https://redmine.openpne.jp/issues/3722

isaosano fix opDynamicAclRoute throws fatal error when using allow_emptyoption (fixes #3722, BP form #3507)

---

lib/routing/opDynamicAclRoute.class.php

bug tichet http://redmine.openpne.jp/issues/3507
BP tichet http://redmine.openpne.jp/issues/3721

fix opDynamicAclRoute throws fatal error when using allow_empty option (fixes #3721, BP from #3507)

---

lib/vendor/PEAR/Archive/Tar.php

https://redmine.openpne.jp/issues/3928
Backport（バックポート） #3928 PHP 5.5 以降でプラグインの展開に失敗する

updated PEAR::Archive_Tar to 1.4.2 for avoiding error on extracting file with PHP 5.5+ (fixes #3928, refs #3918)

---

lib/vendor/PEAR/Archive/Tar.php

https://redmine.openpne.jp/issues/3927
Backport（バックポート） #3927 PHP 5.5 以降でプラグインの展開に失敗する

updated PEAR::Archive_Tar to 1.4.2 for avoiding error on extracting file with PHP 5.5+ (fixes #3927, refs #3918)

---

apps/mobile_frontend/modules/member/templates/profileSuccess.php
apps/pc_frontend/modules/member/templates/_profileListBox.php
plugins/opSkinBasicPlugin/web/css/main.css

Backport (バックポート) #2573: 「プロフィール編集」で編集できるニックネームが「プロフィール確認」のテーブルに表示されない
https://redmine.openpne.jp/issues/2573

(fixes #2573, BP from #2494) added nickname to profile page

---

apps/mobile_frontend/modules/member/templates/profileSuccess.php
apps/pc_frontend/modules/member/templates/_profileListBox.php
plugins/opSkinBasicPlugin/web/css/main.css

Backport (バックポート) #3640: 「プロフィール編集」で編集できるニックネームが「プロフィール確認」のテーブルに表示されない
https://redmine.openpne.jp/issues/3640

(fixes #3640, BP from #2494) added nickname to profile page

---

apps/pc_frontend/templates/_layout.php
apps/pc_frontend/templates/smtLayoutGroup.php
apps/pc_frontend/templates/smtLayoutHome.php
apps/pc_frontend/templates/smtLayoutMember.php
apps/pc_frontend/templates/smtLayoutSns.php

Backport (バックポート) #3989: OpenPNEが設置されているURLをJavaScriptコードから取得できるようにする
https://redmine.openpne.jp/issues/3989

add openpne.baseUrl for client-side rendering (fixes #3989, BP from #3365)

---

web/css/smt_main.css

[Bug ticket]
http://redmine.openpne.jp/issues/3734
[BP ticket]
http://redmine.openpne.jp/issues/3868

(refs #3868, BP from #3734) added style 'overflow: hidden;' for 'row_membername' class in smt_main.css

---

lib/util/opToolkit.class.php

bug ticket http://redmine.openpne.jp/issues/3966
BP ticket http://redmine.openpne.jp/issues/4029

(fixed #4029, BP from #3966) Internet Explorer 11 にてダウンロード時に日本語ファイル名が文字化けする

---

lib/plugins/sfImageHandlerPlugin/lib/image/generator/sfImageGeneratorImageTransform.php

[Bug ticket]
http://redmine.openpne.jp/issues/3195
[BP ticket]
http://redmine.openpne.jp/issues/3859

[sfImageHandlerPlugin] sfImageGeneratorImageTransform::doResize() causes an error when using ImageMagick (fixes #3859, BP from #3195)

---

data/patches/t1565.patch
lib/vendor/symfony/lib/request/sfWebRequest.class.php

Backport (バックポート) #3973: #2316 「update symfony to 1.4.13 (同梱のsymfonyのバージョンを1.4.13へ上げる)」により一部修正が巻き戻ってしまっている．
https://redmine.openpne.jp/issues/3973

(fixes #3973, BP from #2780) add patch to symfony-1.4.13 and repatch #1565 to symfony for avoding http://trac.symfony-project.org/ticket/9061 problem

---

lib/util/opToolkit.class.php

bug ticket http://redmine.openpne.jp/issues/3966
BP ticket http://redmine.openpne.jp/issues/4030

(fixed #4030, BP from #3966) Internet Explorer 11 にてダウンロード時に日本語ファイル名が文字化けする

---

lib/form/MemberConfigForm/MemberConfigPublicFlagForm.class.php
lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #3494: 管理画面で「Web 全体への年齢公開許可設定」を「メンバーの設定を許可しない」に設定しても新規登録時には選択できてしまう
https://redmine.openpne.jp/issues/3494

apply is_allow_web_public_flag_age setting to register-input form (fixes #3494, BP from #3453)

---

lib/plugin/opPlugin.class.php
lib/plugin/opPluginManager.class.php

Bug (バグ) #3352: プラグインチャンネルサーバに接続できない場合に管理画面のプラグインリスト画面が表示できない場合がある
https://redmine.openpne.jp/issues/3352
Backport（バックポート） #4038: プラグインチャンネルサーバに接続できない場合に管理画面のプラグインリスト画面が表示できない場合がある
https://redmine.openpne.jp/issues/4038

retrieve only cached package info for opPlugin::__construct() (fixes #4038, BP from #3352)

---

.gitignore

Bug（バグ） #3354: .gitignore に重複する記述がある
https://redmine.openpne.jp/issues/3354
Backport（バックポート） #4041: .gitignore に重複する記述がある
https://redmine.openpne.jp/issues/4041

delete the duplicate line 'web/cache/*' (fixes #4041,BP from #3354)

---

apps/pc_backend/modules/community/actions/actions.class.php
lib/model/doctrine/Community.class.php
lib/model/doctrine/CommunityMemberTable.class.php

Bug（バグ） #927
「全メンバーをコミュニティ参加させる」リンクによって招待済みで登録していないメンバが登録できなくなる場合がある
https://redmine.openpne.jp/issues/4051
Backport（バックポート） #4051
「全メンバーをコミュニティ参加させる」リンクによって招待済みで登録していないメンバが登録できなくなる場合がある
https://redmine.openpne.jp/issues/4051

improved performance while join all members to community (fixes #4051, BP from #927)

---

apps/pc_backend/i18n/form_community.ja.xml

Bugチケット: https://redmine.openpne.jp/issues/4107
Backportチケット: https://redmine.openpne.jp/issues/4117

(fixed #4117, BP from #4107) max_length のエラーメッセージを翻訳カタログに追加

---

lib/form/MemberConfigForm/MemberConfigPublicFlagForm.class.php
lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #3493: 管理画面で「Web 全体への年齢公開許可設定」を「メンバーの設定を許可しない」に設定しても新規登録時には選択できてしまう
https://redmine.openpne.jp/issues/3493

apply is_allow_web_public_flag_age setting to register-input form (fixes #3493, BP from #3453)

---

lib/plugin/opPlugin.class.php
lib/plugin/opPluginManager.class.php

Backport (バックポート) #4039: プラグインチャンネルサーバに接続できない場合に管理画面のプラグインリスト画面が表示できない場合がある
https://redmine.openpne.jp/issues/4039

retrieve only cached package info for opPlugin::__construct() (fixes #4039, BP from #3352)

---

.gitignore

Bug（バグ） #3354: .gitignore に重複する記述がある
https://redmine.openpne.jp/issues/3354
Backport（バックポート） #4042: .gitignore に重複する記述がある
https://redmine.openpne.jp/issues/4042

delete the duplicate line 'web/cache/*' (fixes #4042,BP from #3354)

---

apps/pc_backend/modules/community/actions/actions.class.php
lib/model/doctrine/Community.class.php
lib/model/doctrine/CommunityMemberTable.class.php

Bug（バグ） #927
「全メンバーをコミュニティ参加させる」リンクによって招待済みで登録していないメンバが登録できなくなる場合がある
https://redmine.openpne.jp/issues/4051
Backport（バックポート） #4052
「全メンバーをコミュニティ参加させる」リンクによって招待済みで登録していないメンバが登録できなくなる場合がある
https://redmine.openpne.jp/issues/4052

improved performance while join all members to community (fixes #4052, BP from #927) 

---

apps/pc_backend/i18n/form_community.ja.xml

Bugチケット: https://redmine.openpne.jp/issues/4107
Backportチケット: https://redmine.openpne.jp/issues/4118

(fixed #4118, BP from #4107) max_length のエラーメッセージを翻訳カタログに追加

---

lib/i18n/opI18N.class.php
test/unit/i18n/opI18nTest.php

Backport (バックポート) #4228: opI18N::__() のパラメータに語形変化の設定をしたSnsTermインスタンスを渡しても反映されない
https://redmine.openpne.jp/issues/4228

allow passing null to opI18N::__() method (fixes #4228, BP from #4168)

---

lib/i18n/opI18N.class.php
test/unit/i18n/opI18nTest.php

Backport (バックポート) #4229: opI18N::__() のパラメータに語形変化の設定をしたSnsTermインスタンスを渡しても反映されない
https://redmine.openpne.jp/issues/4229

allow passing null to opI18N::__() method (fixes #4229, BP from #4168)

---

lib/form/doctrine/NotificationMailTranslationForm.class.php

チケット: https://redmine.openpne.jp/issues/2909

(fixed #2909) メール通知テンプレート設定のタイトルの文字数チェックを行うように変更

---

apps/pc_backend/modules/community/actions/actions.class.php

Bugチケット: https://redmine.openpne.jp/issues/4105

(fixed #4105) コミュニティカテゴリ設定 カテゴリ名称変更時のエラーメッセージが翻訳されるように修正

---

lib/i18n/opI18N.class.php
test/unit/i18n/opI18nTest.php

Bug (バグ) #4168: opI18N::__() のパラメータに語形変化の設定をしたSnsTermインスタンスを渡しても反映されない
https://redmine.openpne.jp/issues/4168

allow passing null to opI18N::__() method (fixes #4168)

---

lib/form/MemberConfigForm/MemberConfigMobileAddressForm.class.php
lib/form/MemberConfigForm/MemberConfigPcAddressForm.class.php

Backport (バックポート) #4148: メールアドレス変更を行うと member_config に name='captcha' のレコードが追加される
https://redmine.openpne.jp/issues/4148

don't save captcha value to member_config (fixes #4148, BP from #4013)

---

lib/form/MemberConfigForm/MemberConfigMobileAddressForm.class.php
lib/form/MemberConfigForm/MemberConfigPcAddressForm.class.php

Backport (バックポート) #4149: メールアドレス変更を行うと member_config に name='captcha' のレコードが追加される
https://redmine.openpne.jp/issues/4149

don't save captcha value to member_config (fixes #4149, BP from #4013)

---

i18n/messages.ja.xml
lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #4044: MemberConfigFormとMemberProfileFormでIsUnique制約に対するエラーメッセージが統一されていない
https://redmine.openpne.jp/issues/4044
Backport (バックポート) #4046: MemberConfigFormのIsUnique制約に対するエラーメッセージが適切に出力されていない
https://redmine.openpne.jp/issues/4046
上記のバグチケットに対する修正です。一方のみの修正ではコンフリクトが生じるため 1 つの Pull Request にまとめています。

MemberConfigForm::isUnique() のエラーメッセージの翻訳に関する複数の修正 (fixes #4044, #4046; BP from #3999, #4000)

---

i18n/messages.ja.xml
lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #4043: MemberConfigFormとMemberProfileFormでIsUnique制約に対するエラーメッセージが統一されていない
https://redmine.openpne.jp/issues/4043
Backport (バックポート) #4045: MemberConfigFormのIsUnique制約に対するエラーメッセージが適切に出力されていない
https://redmine.openpne.jp/issues/4045
上記のバグチケットに対する修正です。一方のみの修正ではコンフリクトが生じるため 1 つの Pull Request にまとめています。

MemberConfigForm::isUnique() のエラーメッセージの翻訳に関する複数の修正 (fixes #4043, #4045; BP from #3999, #4000)

---

i18n/messages.ja.xml
lib/form/doctrine/MemberConfigForm.class.php

Bug (バグ) #3999: MemberConfigFormとMemberProfileFormでIsUnique制約に対するエラーメッセージが統一されていない
https://redmine.openpne.jp/issues/3999
Bug (バグ) #4000: MemberConfigFormのIsUnique制約に対するエラーメッセージが適切に出力されていない
https://redmine.openpne.jp/issues/4000
上記のバグチケットに対する修正です。一方のみの修正ではコンフリクトが生じるため 1 つの Pull Request にまとめています。

MemberConfigForm::isUnique() のエラーメッセージの翻訳に関する複数の修正 (fixes #3999, #4000)

---

lib/vendor/PEAR/XML/Util.php

Bug（バグ） #1300
./symfony opPlugin:define 時に XML/Util.php がないとエラーが出る。
https://redmine.openpne.jp/issues/1300
Backport（バックポート） #4049
./symfony opPlugin:define 時に XML/Util.php がないとエラーが出る。
https://redmine.openpne.jp/issues/4049

(fixed #4049, BP from #1300) added PEAR/XML/Util.php

---

lib/vendor/PEAR/XML/Util.php

Bug（バグ） #1300
./symfony opPlugin:define 時に XML/Util.php がないとエラーが出る。
https://redmine.openpne.jp/issues/1300
Backport（バックポート） #4050
./symfony opPlugin:define 時に XML/Util.php がないとエラーが出る。
https://redmine.openpne.jp/issues/4050

(fixed #4050, BP from #1300) added PEAR/XML/Util.php

---

plugins/opAuthMailAddressPlugin/lib/form/opAuthRegisterFormMailAddress.class.php

Bug（バグ） #3504
新規登録時に「秘密の質問への答え」が空欄のままでも登録できてしまう
https://redmine.openpne.jp/issues/3504
Closes #228

add a requirement not to register the secret password with null character (fixes #3504)

---

apps/pc_frontend/modules/member/templates/configCompleteSuccess.php
lib/action/opMemberAction.class.php
lib/model/doctrine/MemberConfig.class.php
test/functional/pc_frontend/memberConfigConfirmTest.php

Backport (バックポート) #4015: メールアドレス変更処理が完了しても、仮登録用のデータ (`***_pre`, `***_token`) が MemberConfig に残ってしまい、削除されない
https://redmine.openpne.jp/issues/4015
Backport (バックポート) #4017: メールアドレス設定から意図的に他のメンバーと同じメールアドレスを設定できる
https://redmine.openpne.jp/issues/4017
上記のバグチケットに対する修正を含んでいます。

メールアドレス変更に関する複数の修正 (fixes #4015, #4017; BP from #3077, #4012)

---

lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #4146: member/registerInputアクションでメンバー登録のフォームを生成する際にE_NOTICEエラーが発生する
https://redmine.openpne.jp/issues/4146

set default settings when retrieving openpne_member_config (fixes #4146, BP from #4034)

---

apps/pc_frontend/modules/member/templates/configCompleteSuccess.php
lib/action/opMemberAction.class.php
lib/model/doctrine/MemberConfig.class.php
test/functional/pc_frontend/memberConfigConfirmTest.php

Backport (バックポート) #4016: メールアドレス変更処理が完了しても、仮登録用のデータ (`***_pre`, `***_token`) が MemberConfig に残ってしまい、削除されない
https://redmine.openpne.jp/issues/4016
Backport (バックポート) #4018: メールアドレス設定から意図的に他のメンバーと同じメールアドレスを設定できる
https://redmine.openpne.jp/issues/4018
上記のバグチケットに対する修正を含んでいます。

メールアドレス変更に関する複数の修正 (fixes #4016, #4018; BP from #3077, #4012)

---

lib/form/doctrine/MemberConfigForm.class.php

Backport (バックポート) #4147: member/registerInputアクションでメンバー登録のフォームを生成する際にE_NOTICEエラーが発生する
https://redmine.openpne.jp/issues/4147

set default settings when retrieving openpne_member_config (fixes #4147, BP from #4034)

---

apps/pc_frontend/modules/member/templates/configCompleteSuccess.php
lib/action/opMemberAction.class.php
lib/model/doctrine/MemberConfig.class.php
test/functional/pc_frontend/memberConfigConfirmTest.php

Bug (バグ) #3077: メールアドレス変更処理が完了しても、仮登録用のデータ (***_pre, ***_token) が MemberConfig に残ってしまい、削除されない
https://redmine.openpne.jp/issues/3077
Bug (バグ) #4012: メールアドレス設定から意図的に他のメンバーと同じメールアドレスを設定できる
https://redmine.openpne.jp/issues/4012
上記のバグチケットに対する修正を含んでいます。

メールアドレス変更に関する複数の修正 (fixes #3077, #4012)

---

apps/pc_backend/i18n/messages.ja.xml
apps/pc_backend/modules/navigation/templates/listSuccess.php
apps/pc_backend/modules/sns/actions/actions.class.php
apps/pc_frontend/modules/default/templates/_globalNav.php
apps/pc_frontend/modules/default/templates/_localNav.php
data/fixtures/004_import_navi_menu.yml
test/fixtures/common/test_data.yml

http://redmine.openpne.jp/issues/4099 が適用されていることが必要です

(fixed #4269, BP from #4267) SNS内名称設定を行った際、navigation のキャッシュクリアを行うように変更

---

apps/pc_backend/i18n/messages.ja.xml
apps/pc_backend/modules/navigation/templates/listSuccess.php
apps/pc_backend/modules/sns/actions/actions.class.php
apps/pc_frontend/modules/default/templates/_globalNav.php
apps/pc_frontend/modules/default/templates/_localNav.php
data/fixtures/004_import_navi_menu.yml
test/fixtures/common/test_data.yml

http://redmine.openpne.jp/issues/4100 が適用されていることが必要です

(fixed #4270, BP from #4267) SNS内名称設定を行った際、navigation のキャッシュクリアを行うように変更

---

apps/api/lib/helper/opJsonApiHelper.php
test/functional/api/pushSearchActionTest.php

Bug (バグ) #4055: OpenPNE が http://example.com/sns/ のようにサブディレクトリ以下に設置されている場合に、通知センターからアクセスする日記やコミュニティのURLが正しくない
https://redmine.openpne.jp/issues/4055
Backport ticket
http://redmine.openpne.jp/issues/4379

allow internal uri (the 'url_for()' format) for notification url (fixes #4379, BP from #4055)

---

lib/helper/opJavascriptHelper.php

Bug（バグ） #4031
存在しない /js/.js を読み込もうとして404エラーが発生している
http://redmine.openpne.jp/issues/4031
Backport（バックポート） #4381
存在しない /js/.js を読み込もうとして404エラーが発生している
http://redmine.openpne.jp/issues/4381

fix reference to non-existence .js file (fixes #4381, BP from #4031)

---

lib/config/opApplicationConfiguration.class.php
lib/i18n/opI18N.class.php
lib/model/doctrine/SnsTermTable.class.php

SnsTermTable::configure() で pc_backend, api が指定される可能性をなくし、言語アプリケーション切替時は取得済みの terms を空にする

(refs #4672, BP from #4668) SNS内名称設定で設定されている項目が翻訳されない場合がある

---

lib/config/opApplicationConfiguration.class.php
lib/i18n/opI18N.class.php
lib/model/doctrine/SnsTermTable.class.php

SnsTermTable::configure() で pc_backend, api が指定される可能性をなくし、言語アプリケーション切替時は取得済みの terms を空にする

(refs #4671, BP from #4668) SNS内名称設定で設定されている項目が翻訳されない場合がある

---

lib/config/opApplicationConfiguration.class.php
lib/i18n/opI18N.class.php
lib/model/doctrine/SnsTermTable.class.php

(refs #4668) SnsTermTable::configure() で pc_backend, api が指定される可能性をなくし、言語アプリケーション切替時は取得済みの terms を空にする

(refs #4668) SNS内名称設定で設定されている項目が翻訳されない場合がある
