web/cmd/jp.youtube.com.js
web/cmd/www.youtube.com.js
web/cmd/youtube.js

bug ticket http://redmine.openpne.jp/issues/3414
BP ticket http://redmine.openpne.jp/issues/3779

(refs #3779, BP from #3414) To use the videos embedded in an iframe element of on YouTube small window

---

lib/model/doctrine/ActivityData.class.php
lib/model/doctrine/ActivityImage.class.php
lib/model/doctrine/BannerImage.class.php
lib/model/doctrine/Community.class.php
lib/model/doctrine/OAuthConsumerInformation.class.php
test/bootstrap/database.php
test/fixtures/common/test_data.yml
test/unit/model/doctrine/ActivityDataTest.php
test/unit/model/doctrine/BannerImageTest.php
test/unit/model/doctrine/CommunityTest.php
test/unit/model/doctrine/OAuthConsumerInformationTest.php

bug ticket http://redmine.openpne.jp/issues/3738
BP ticket http://redmine.openpne.jp/issues/3767

(refs #3767, BP from #3738) Fixed a bug that when deleting records in the table that refers to the file is not deleted

---

web/js/jquery.notify.js

bug ticket http://redmine.openpne.jp/issues/3411
BP ticket http://redmine.openpne.jp/issues/3760

(refs #3760, BP from #3411) Bug fixes the display of all of the notification is changed when it was approved for Friends request

---

web/cmd/jp.youtube.com.js
web/cmd/www.youtube.com.js
web/cmd/youtube.js

bug ticket http://redmine.openpne.jp/issues/3414
BP ticket http://redmine.openpne.jp/issues/3780

(refs #3780, BP from #3414) To use the videos embedded in an iframe element of on YouTube small window

---

lib/model/doctrine/ActivityData.class.php
lib/model/doctrine/ActivityImage.class.php
lib/model/doctrine/BannerImage.class.php
lib/model/doctrine/Community.class.php
lib/model/doctrine/OAuthConsumerInformation.class.php
test/bootstrap/database.php
test/fixtures/common/test_data.yml
test/unit/model/doctrine/ActivityDataTest.php
test/unit/model/doctrine/BannerImageTest.php
test/unit/model/doctrine/CommunityTest.php
test/unit/model/doctrine/OAuthConsumerInformationTest.php

bug ticket http://redmine.openpne.jp/issues/3738
BP ticket http://redmine.openpne.jp/issues/3772

(refs #3772, BP from #3738) Fixed a bug that when deleting records in the table that refers to the file is not deleted

---

apps/pc_frontend/modules/member/config/view.yml

bug ticket http://redmine.openpne.jp/issues/3595
BP ticket http://redmine.openpne.jp/issues/3761

(refs #3761, BP from #3595) output util.js once

---

plugins/sfImageHandlerPlugin/lib/image/generator/sfImageGenerator.class.php

bug ticket http://redmine.openpne.jp/issues/2228
BP ticket http://redmine.openpne.jp/issues/3785

(refs #3785, BP from #2228) correct wrong class name in sfImageHandlerPlugin

---

lib/form/doctrine/MemberProfileForm.class.php

bug ticket http://redmine.openpne.jp/issues/3602
BP ticket http://redmine.openpne.jp/issues/3793

(refs #3793, BP from #3602) Fixed a bug that if profile input value is empty, there are items that visibility is not changed.

---

lib/form/doctrine/MemberProfileForm.class.php

bug ticket http://redmine.openpne.jp/issues/3602
BP ticket http://redmine.openpne.jp/issues/3794

(refs #3794, BP from #3602) Fixed a bug that if profile input value is empty, there are items that visibility is not changed.

---

apps/mobile_frontend/modules/community/actions/actions.class.php
apps/pc_frontend/modules/community/actions/actions.class.php
lib/action/opCommunityAction.class.php

bug ticket : http://redmine.openpne.jp/issues/3588
BP ticket : http://redmine.openpne.jp/issues/3729

fix not to create empty Community( except image) if a Community created by smartphone(refs #3729, BP from #3588)

---

lib/config/opProjectConfiguration.class.php

bug ticket http://redmine.openpne.jp/issues/3391

(fixes #3391) In the test environment it was not allowed to override the session storage settings that are defined in the factories.yml

---

lib/config/opProjectConfiguration.class.php

bug ticket http://redmine.openpne.jp/issues/3391
BP ticket http://redmine.openpne.jp/issues/3814

(refs #3814, BP from #3391) In the test environment it was not allowed to override the session storage settings that are defined in the factories.yml

---

apps/pc_backend/modules/advanced/lib/opRichTextareaOpenPNEConfigForm.class.php
apps/pc_backend/modules/design/lib/PickHomeLayoutForm.class.php
apps/pc_backend/modules/mail/lib/opMailNotificationForm.class.php
apps/pc_backend/modules/member/lib/AdminInviteForm.class.php
apps/pc_backend/modules/plugin/lib/PluginActivationForm.class.php
lib/form/MemberConfigForm/MemberConfigMailForm.class.php
lib/form/doctrine/ActivityDataForm.class.php
lib/form/doctrine/BannerForm.class.php
lib/form/doctrine/CommunityConfigForm.class.php
lib/form/doctrine/OAuthConsumerInformationForm.class.php
lib/form/doctrine/ProfileForm.class.php
lib/form/doctrine/opPermitMemberConfigSnsConfigForm.class.php
lib/form/opLanguageSelecterForm.class.php
lib/form/opPresetProfileForm.class.php
lib/validator/opValidatorChoice.class.php
lib/validator/opValidatorProfile.class.php
plugins/opAuthMailAddressPlugin/lib/form/opAuthMailAddressPasswordRecoveryForm.class.php
test/unit/validator/opValidatorChoiceTest.php

bug ticket http://redmine.openpne.jp/issues/3401
BP ticket http://redmine.openpne.jp/issues/3811

(refs #3811, BP from #3401) Bug Fixed a validation of sfValidatorChoice

---

lib/config/opProjectConfiguration.class.php

bug ticket http://redmine.openpne.jp/issues/3391
BP ticket http://redmine.openpne.jp/issues/3813

(refs #3813, BP from #3391) In the test environment it was not allowed to override the session storage settings that are defined in the factories.yml

---

apps/pc_backend/modules/design/lib/PickHomeLayoutForm.class.php
apps/pc_backend/modules/mail/lib/opMailNotificationForm.class.php
apps/pc_backend/modules/member/lib/AdminInviteForm.class.php
apps/pc_backend/modules/plugin/lib/PluginActivationForm.class.php
lib/form/MemberConfigForm/MemberConfigMailForm.class.php
lib/form/doctrine/ActivityDataForm.class.php
lib/form/doctrine/BannerForm.class.php
lib/form/doctrine/CommunityConfigForm.class.php
lib/form/doctrine/OAuthConsumerInformationForm.class.php
lib/form/doctrine/ProfileForm.class.php
lib/form/doctrine/opPermitMemberConfigSnsConfigForm.class.php
lib/form/opLanguageSelecterForm.class.php
lib/form/opPresetProfileForm.class.php
lib/util/opFormItemGenerator.class.php
lib/validator/opValidatorChoice.class.php
lib/validator/opValidatorProfile.class.php
test/unit/validator/opValidatorChoiceTest.php

bug ticket http://redmine.openpne.jp/issues/3401
BP ticket http://redmine.openpne.jp/issues/3810

(refs #3810, BP from #3401) Bug Fixed a validation of sfValidatorChoice

---

apps/pc_backend/modules/design/lib/PickHomeLayoutForm.class.php

bug ticket http://redmine.openpne.jp/issues/3492
BP ticket http://redmine.openpne.jp/issues/3866

(refs #3866, BP from #3492) repair the return value exactly

---

apps/api/modules/activity/actions/actions.class.php

bug ticket https://redmine.openpne.jp/issues/3260
BP ticket https://redmine.openpne.jp/issues/3727

include friend's and my activities in activity/search.json (fixes #3727, BP from #3260)

---

apps/api/modules/activity/actions/actions.class.php

bug ticket http://redmine.openpne.jp/issues/3245
BP ticket http://redmine.openpne.jp/issues/3249

(refs #3249, BP form #3245) fixed to reflect the activity/post settings.

---

apps/pc_frontend/modules/member/templates/_profileListBox.php

[bug ticket]
https://redmine.openpne.jp/issues/2661
[BP ticket]
https://redmine.openpne.jp/issues/3858

show the age at the profile page correctly(fixes #3858, BP from #2661)

---

apps/pc_backend/modules/design/lib/PickHomeLayoutForm.class.php

bug ticket http://redmine.openpne.jp/issues/3492
BP ticket http://redmine.openpne.jp/issues/3865

(refs #3865, BP from #3492) repair the return value exactly

---

apps/pc_frontend/modules/member/templates/_profileListBox.php

[bug ticket]
https://redmine.openpne.jp/issues/2661
[BP ticket]
https://redmine.openpne.jp/issues/3857

show the age at the profile page correctly(fixes #3857, BP from #2661)

---

web/cmd/maps.google.co.jp.js
web/cmd/maps.google.com.js
web/cmd/www.google.co.jp.js
web/cmd/www.google.com.js

【Enhancement ticket】
https://redmine.openpne.jp/issues/3775
【Backport ticket】
https://redmine.openpne.jp/issues/3892

Modified to be able to display the URL of the new format of the Googlemap (refs #3892, BP from #3775)

---

web/cmd/maps.google.co.jp.js
web/cmd/maps.google.com.js
web/cmd/www.google.co.jp.js
web/cmd/www.google.com.js

【Enhancement ticket】
https://redmine.openpne.jp/issues/3775
【Backport ticket】
https://redmine.openpne.jp/issues/3891

Modified to be able to display the URL of the new format of the Googlemap (refs #3891, BP from #3775)

---

doc/en/OpenPNE3_Setup_Guide.txt
doc/ja/OpenPNE3_Setup_Guide.txt

【Bug ticket】
https://redmine.openpne.jp/issues/3941
【BP ticket】
https://redmine.openpne.jp/issues/3939

Add a description of exif module in the Setup Guide (refs #3941, BP from #3939)

---

doc/en/OpenPNE3_Setup_Guide.txt
doc/ja/OpenPNE3_Setup_Guide.txt

【Bug ticket】
https://redmine.openpne.jp/issues/3939
【BP ticket】
https://redmine.openpne.jp/issues/3940

Add a description of exif module in the Setup Guide (refs #3940, BP from #3939)

---

doc/en/OpenPNE3_Setup_Guide.txt
doc/ja/OpenPNE3_Setup_Guide.txt

bug ticket http://redmine.openpne.jp/issues/3957
BP ticket http://redmine.openpne.jp/issues/3974

(refs #3974, BP from #3957) add APCu extension to recommendations in install guide

---

web/cmd/amazon.co.jp.js
web/cmd/www.amazon.co.jp.js

https://redmine.openpne.jp/issues/3995
に対する修正です。

(refs #3995, BP from #3993) changed url of cmd-amazon from http://amazon.openpne.jp/ to https://amazon.openpne.jp/

---

apps/pc_frontend/templates/_layout.php
web/js/smt_main.js

bug ticket http://redmine.openpne.jp/issues/3364
BP ticket http://redmine.openpne.jp/issues/3714

fix bug in switching smartphone/PC layout (fix #3714, BP from #3364)

---

doc/en/OpenPNE3_Setup_Guide.txt
doc/ja/OpenPNE3_Setup_Guide.txt

bug ticket http://redmine.openpne.jp/issues/3957
BP ticket http://redmine.openpne.jp/issues/3975

(refs #3975, BP from #3957) add APCu extension to recommendations in install guide

---

apps/pc_frontend/modules/member/templates/_smtProfileListBox.php

bug ticket http://redmine.openpne.jp/issues/3955
BP ticket http://redmine.openpne.jp/issues/3977

(refs #3977, BP from #3955) added culture to template for smartphone.

---

web/cmd/amazon.co.jp.js
web/cmd/www.amazon.co.jp.js

https://redmine.openpne.jp/issues/3994
に対する修正です。

(refs #3994, BP from  #3993) changed url of cmd-amazon from http://amazon.openpne.jp/ to https://amazon.openpne.jp/

---

lib/form/doctrine/MemberConfigForm.class.php

bug ticket http://redmine.openpne.jp/issues/2489
BP ticket http://redmine.openpne.jp/issues/2571

(fixes #2571, BP from #2489) changed MemberConfigForm::setMemberConfigWidget()

---

lib/form/doctrine/MemberConfigForm.class.php

bug ticket http://redmine.openpne.jp/issues/2489
BP ticket http://redmine.openpne.jp/issues/3185

(fixes #3185, BP from #2489) changed MemberConfigForm::setMemberConfigWidget()

---

lib/util/opBrowser.class.php

bug ticket http://redmine.openpne.jp/issues/3852
BP ticket http://redmine.openpne.jp/issues/3980

(refs #3980, BP from #3852) clear MemberConfig caches on every request by opBrowser

---

apps/pc_backend/modules/mail/actions/actions.class.php
apps/pc_backend/modules/mail/templates/configSuccess.php

Bugチケット: https://redmine.openpne.jp/issues/4106
Backportチケット: https://redmine.openpne.jp/issues/4115

(fixed #4115, BP from #4106) メール通知送信設定 のエラーメッセージ表示方法を変更

---

apps/pc_backend/i18n/messages.ja.xml
apps/pc_backend/modules/member/actions/actions.class.php
apps/pc_backend/modules/member/templates/deleteSuccess.php
apps/pc_backend/modules/member/templates/listSuccess.php
apps/pc_backend/modules/member/templates/rejectSuccess.php
templates/_deleteAccountMail.php

Bugチケット: https://redmine.openpne.jp/issues/4128
Backportチケット: https://redmine.openpne.jp/issues/4129

(fixed #4129, BP from #4128) ニックネームをSNS内名称設定に対応するよう修正

---

lib/util/opOAuthDataStore.class.php

bug ticket http://redmine.openpne.jp/issues/3232
BP ticket http://redmine.openpne.jp/issues/3706

(fixes #3706,BP from #3232) fixed to get secret key when request token was looked up in datastore

---

lib/util/opBrowser.class.php

bug ticket http://redmine.openpne.jp/issues/3852
BP ticket http://redmine.openpne.jp/issues/3981

(refs #3981, BP from #3852) clear MemberConfig caches on every request by opBrowser

---

apps/pc_backend/modules/mail/actions/actions.class.php
apps/pc_backend/modules/mail/templates/configSuccess.php

Bugチケット: https://redmine.openpne.jp/issues/4106
Backportチケット: https://redmine.openpne.jp/issues/4116

(fixed #4116, BP from #4106) メール通知送信設定 のエラーメッセージ表示方法を変更

---

apps/pc_backend/i18n/messages.ja.xml
apps/pc_backend/modules/member/actions/actions.class.php
apps/pc_backend/modules/member/templates/deleteSuccess.php
apps/pc_backend/modules/member/templates/listSuccess.php
apps/pc_backend/modules/member/templates/rejectSuccess.php
templates/_deleteAccountMail.php

Bugチケット: https://redmine.openpne.jp/issues/4128
Backportチケット: https://redmine.openpne.jp/issues/4130

(fixed #4130, BP from #4128) ニックネームをSNS内名称設定に対応するよう修正

---

apps/pc_frontend/modules/member/templates/registerInputSuccess.php
web/js/util.js
web/js/util.js.src

Backport (バックポート) #3186: メンバー登録時にデータが不正な状態になることがある
https://redmine.openpne.jp/issues/3186

prevent double submission on member/registerInput form (fixes #3186, BP from #3150)

---

apps/pc_frontend/modules/member/templates/registerInputSuccess.php
web/js/util.js
web/js/util.js.src

Backport (バックポート) #3184: メンバー登録時にデータが不正な状態になることがある
https://redmine.openpne.jp/issues/3184

prevent double submission on member/registerInput form (fixes #3184, BP from #3150)

---

lib/action/opMemberAction.class.php

Bug チケット: https://redmine.openpne.jp/issues/4072
BP チケット: https://redmine.openpne.jp/issues/4097

(fixed #4097, BP from #4072) 未ログイン状態で /member/profile にアクセスした場合にログインフォームを表示するよう修正

---

lib/form/doctrine/NotificationMailTranslationForm.class.php

Enhancementチケット: https://redmine.openpne.jp/issues/2909
Backportチケット: https://redmine.openpne.jp/issues/4108

(fixed #4108, BP from #2909) メール通知テンプレート設定のタイトルの文字数チェックを行うように変更

---

apps/pc_backend/modules/mail/actions/actions.class.php
apps/pc_backend/modules/mail/templates/templateSuccess.php

Bugチケット: https://redmine.openpne.jp/issues/4104
Backportチケット: https://redmine.openpne.jp/issues/4110

(fixed #4110, BP from #4104) メール通知テンプレート設定 のエラーメッセージ表示方法を変更

---

apps/pc_backend/modules/community/actions/actions.class.php

Bugチケット: https://redmine.openpne.jp/issues/4105
Backportチケット: https://redmine.openpne.jp/issues/4113

(fixed #4113, BP from #4105) コミュニティカテゴリ設定 カテゴリ名称変更時のエラーメッセージが翻訳されるように修正

---

lib/action/opMemberAction.class.php

Bug チケット: https://redmine.openpne.jp/issues/4072
BP チケット: https://redmine.openpne.jp/issues/4098

(fixed #4098, BP from #4072) 未ログイン状態で /member/profile にアクセスした場合にログインフォームを表示するよう修正

---

lib/form/doctrine/NotificationMailTranslationForm.class.php

Enhancementチケット: https://redmine.openpne.jp/issues/2909
Backportチケット: https://redmine.openpne.jp/issues/4109

(fixed #4109, BP from #2909) メール通知テンプレート設定のタイトルの文字数チェックを行うように変更

---

apps/pc_backend/modules/mail/actions/actions.class.php
apps/pc_backend/modules/mail/templates/templateSuccess.php

Bugチケット: https://redmine.openpne.jp/issues/4104
Backportチケット: https://redmine.openpne.jp/issues/4111

(fixed #4111, BP from #4104) メール通知テンプレート設定 のエラーメッセージ表示方法を変更

---

apps/pc_backend/modules/community/actions/actions.class.php

Bugチケット: https://redmine.openpne.jp/issues/4105
Backportチケット: https://redmine.openpne.jp/issues/4114

(fixed #4114, BP from #4105) コミュニティカテゴリ設定 カテゴリ名称変更時のエラーメッセージが翻訳されるように修正

---

apps/pc_frontend/templates/smtLayoutGroup.php
apps/pc_frontend/templates/smtLayoutHome.php
apps/pc_frontend/templates/smtLayoutMember.php
apps/pc_frontend/templates/smtLayoutSns.php

…ncated to its numeric prefix.

 (refs #4209, BP from #4183) The value "320px" for key "width" was truncated to its numeric prefix.

---

apps/mobile_frontend/i18n/messages.ja.xml
apps/mobile_frontend/i18n/publicFlags.ja.xml
apps/mobile_frontend/modules/member/templates/profileSuccess.php
apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/i18n/publicFlags.ja.xml
apps/pc_frontend/modules/member/templates/_profileListBox.php
lib/model/doctrine/ActivityDataTable.class.php
lib/model/doctrine/ProfileTable.class.php

Bugチケット: https://redmine.openpne.jp/issues/4143
Backportチケット: https://redmine.openpne.jp/issues/4144

(fixed #4144. BP from #4143) %my_friend% の翻訳を修正

---

lib/widget/opWidgetFormDateTime.class.php

Enhancement (機能追加・改善) #1873: [PATCH] opWidgetFormDateTime クラスの追加
https://redmine.openpne.jp/issues/1873

added opWidgetFormDateTime (fixes #4258, BP from #1873)

---

apps/mobile_frontend/i18n/messages.ja.xml
apps/mobile_frontend/i18n/publicFlags.ja.xml
apps/mobile_frontend/modules/member/templates/profileSuccess.php
apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/i18n/publicFlags.ja.xml
apps/pc_frontend/modules/member/templates/_profileListBox.php
lib/model/doctrine/ActivityDataTable.class.php
lib/model/doctrine/ProfileTable.class.php

Bugチケット: https://redmine.openpne.jp/issues/4143
Backportチケット: https://redmine.openpne.jp/issues/4145

(fixed #4145, BP from #4143) %my_friend% の翻訳を修正

---

lib/widget/opWidgetFormDateTime.class.php

Enhancement (機能追加・改善) #1873: [PATCH] opWidgetFormDateTime クラスの追加
https://redmine.openpne.jp/issues/1873

added opWidgetFormDateTime (fixes #4259, BP from #1873)

---

apps/pc_frontend/modules/member/templates/registerInputSuccess.php
web/js/util.js
web/js/util.js.src

Bug (バグ) #3150: メンバー登録時にデータが不正な状態になることがある
https://redmine.openpne.jp/issues/3150

prevent double submission on member/registerInput form (fixes #3150)

---

apps/pc_backend/modules/mail/actions/actions.class.php
apps/pc_backend/modules/mail/templates/templateSuccess.php

Bugチケット: https://redmine.openpne.jp/issues/4104

(fixed #4104) メール通知テンプレート設定 のエラーメッセージ表示方法を変更

---

lib/action/opMemberAction.class.php

チケット
https://redmine.openpne.jp/issues/4072

(fixed #4072) 未ログイン状態で /member/profile にアクセスした場合にログインフォームを表示するよう修正

---

apps/pc_frontend/templates/smtLayoutGroup.php
apps/pc_frontend/templates/smtLayoutHome.php
apps/pc_frontend/templates/smtLayoutMember.php
apps/pc_frontend/templates/smtLayoutSns.php

(refs #4183) The value "320px" for key "width" was truncated to its numeric prefix.

---

apps/mobile_frontend/i18n/messages.ja.xml
apps/mobile_frontend/i18n/publicFlags.ja.xml
apps/mobile_frontend/modules/member/templates/profileSuccess.php
apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/i18n/publicFlags.ja.xml
apps/pc_frontend/modules/member/templates/_profileListBox.php
lib/model/doctrine/ActivityDataTable.class.php
lib/model/doctrine/ProfileTable.class.php

チケット: https://redmine.openpne.jp/issues/4143

(fixed #4143) %my_friend% の翻訳を修正

---

lib/widget/opWidgetFormDateTime.class.php

Enhancement (機能追加・改善) #1873: [PATCH] opWidgetFormDateTime クラスの追加
https://redmine.openpne.jp/issues/1873

added opWidgetFormDateTime (fixes #1873)

---

lib/form/doctrine/MemberProfileForm.class.php

bug ticket http://redmine.openpne.jp/issues/3602

(refs #3602) Fixed a bug that if profile input value is empty, there are items that visibility is not changed.

---

lib/task/opPluginInstallTask.class.php

【Bug ticket】
https://redmine.openpne.jp/issues/3925
【BP ticket】
https://redmine.openpne.jp/issues/4169

Fix to take the return value into consideration (refs #4169, BP from #3925)

---

apps/pc_frontend/modules/googlemaps/templates/indexSuccess.php

…of Google's document Loading_the_Maps_API.

(refs #4211, BP from #3916) It is in accordance with the description of Google's document Loading_the_Maps_API.

---

lib/task/opPluginInstallTask.class.php

【Bug ticket】
https://redmine.openpne.jp/issues/3925
【BP ticket】
https://redmine.openpne.jp/issues/4170

Fix to take the return value into consideration (refs #4170, BP from #3925)

---

apps/pc_frontend/modules/googlemaps/templates/indexSuccess.php

…of Google's document Loading_the_Maps_API.

(refs #4210, BP from #3916) It is in accordance with the description of Google's document Loading_the_Maps_API.

---

apps/pc_frontend/modules/googlemaps/templates/indexSuccess.php

(refs #3916) It is in accordance with the description of Google's document Loading_the_Maps_API.

---

lib/task/opPluginInstallTask.class.php

Bug ticket
https://redmine.openpne.jp/issues/3925

Fix to take the return value into consideration (refs #3925)

---

plugins/opAuthMailAddressPlugin/lib/form/opAuthRegisterFormMailAddress.class.php

bug ticket http://redmine.openpne.jp/issues/3504
BP ticket http://redmine.openpne.jp/issues/3720

add a requirement not to register the secret password with null character (fixes #3720, BP from #3504)

---

lib/form/doctrine/MemberConfigForm.class.php

Bug (バグ) #4034: member/registerInputアクションでメンバー登録のフォームを生成する際にE_NOTICEエラーが発生する
https://redmine.openpne.jp/issues/4034

set default settings when retrieving openpne_member_config (fixes #4034) 

---

apps/api/config/filters.yml

cherry-pick from 8e3899412af5f7bb6302c344a030f690e7b91f62

(refs #4193, BP from #4174) Added no-cache header in api application.

---

apps/api/lib/helper/opJsonApiHelper.php
apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/templates/_header.php
apps/pc_frontend/templates/_tosaka.php
lib/model/doctrine/MemberRelationship.class.php
lib/util/opNotificationCenter.class.php

[Bug ticket]
http://redmine.openpne.jp/issues/3303
[BP ticket]
http://redmine.openpne.jp/issues/3860

Modify notification center

---

apps/api/lib/helper/opJsonApiHelper.php
apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/templates/_header.php
apps/pc_frontend/templates/_tosaka.php
lib/model/doctrine/MemberRelationship.class.php
lib/util/opNotificationCenter.class.php

Bug ticket
https://redmine.openpne.jp/issues/3303

メンバーがフレンド申請を受け入れても通知が消えない問題に対する対応

---

apps/pc_frontend/config/routing.yml
apps/pc_frontend/config/view.yml
apps/pc_frontend/modules/default/actions/urlForAction.class.php
apps/pc_frontend/templates/_layout.php
web/js/op_url.js
web/js/util.js
web/js/util.js.src

Enhancement（機能追加・改善） #4183
JavaScript から route (app_url_for, url_for) を呼び出せる機能が欲しい
http://redmine.openpne.jp/issues/4183
Backport（バックポート） #4377
JavaScript から route (app_url_for, url_for) を呼び出せる機能が欲しい
http://redmine.openpne.jp/issues/4377

(refs #4377, BP from #4183) url_for, app_url_for for javascript. 

---

apps/pc_backend/i18n/messages.ja.xml
apps/pc_backend/modules/member/actions/actions.class.php
apps/pc_backend/modules/member/templates/inviteSuccess.php
lib/form/doctrine/InvitelistForm.class.php
lib/model/doctrine/MemberConfigTable.class.php

Enhancement（機能追加・改善） #4139
管理画面からの招待メール送信にて送信状況の確認と招待の取り消しを行えるようにして欲しい
http://redmine.openpne.jp/issues/4139
Backport（バックポート） #4376
管理画面からの招待メール送信にて送信状況の確認と招待の取り消しを行えるようにして欲しい
http://redmine.openpne.jp/issues/4376

(fixed #4376, BP from #4139)管理画面からの招待メール送信にて送信状況の確認と招待の取り消しを行えるようにしました

---

apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/modules/community/templates/_smtCommunityListBox.php
apps/pc_frontend/modules/default/templates/_smtMenu.php
data/fixtures/012_import_smartphone_navi_menu.yml
data/migrations/3.8RC1/fixtures/047_insert_smartphone_navigation_and_gadgets.yml

Bugチケット: https://redmine.openpne.jp/issues/4082
BPチケット: https://redmine.openpne.jp/issues/4101

(fixed #4101, BP from #4082) スマートフォン版にてSNS内名称設定に対応していなかった箇所を修正

---

apps/pc_frontend/i18n/messages.ja.xml
apps/pc_frontend/modules/community/templates/_smtCommunityListBox.php
apps/pc_frontend/modules/default/templates/_smtMenu.php
data/fixtures/012_import_smartphone_navi_menu.yml
data/migrations/3.8RC1/fixtures/047_insert_smartphone_navigation_and_gadgets.yml

Bug ticket https://redmine.openpne.jp/issues/4082

(fixed #4378, BP from #4082) スマートフォン版にてSNS内名称設定に対応していなかった箇所を修正
